[pytest]
testpaths = tests
python_files = test*.py
python_functions = test_*
pythonpath = .

# Ignore un DeprecationWarning provenant de spaCy/Click (dépendance externe).
# Ce warning ne vient pas de notre code et n’affecte pas le fonctionnement du projet.
filterwarnings = ignore:Importing 'parser\.split_arg_string' is deprecated.*:DeprecationWarning